CREATE TABLE `Bill` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT,
  `amount` DOUBLE NOT NULL,
  `dueDate` DATETIME(3) NOT NULL,
  `status` VARCHAR(191) NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `paymentProvider` VARCHAR(191),
  `autoRenew` BOOLEAN NOT NULL DEFAULT false,
  `recurrence` VARCHAR(191) NOT NULL DEFAULT 'none',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB;
